### ISSUE TITLE
Errors on Windows 10

### ISSUE THREAD

**Issue by justinbass** [maebert/shellcraft#4]
* ShellCraft version: 0.9.2
* Python version: 2.7.9
* Operating System: Windows 10, running cygwin

### Description

Version 0.6.1 installed and played fine (the old version from a pip install), but 0.92 (latest from git) does not seem to load.

Also unrelated - there are a few typos in the tutorial (doens't, availabel).

### What I Did

```
$ shellcraft
Traceback (most recent call last):
  File "/usr/bin/shellcraft", line 9, in <module>
    load_entry_point('shellcraft==0.9.2', 'console_scripts', 'shellcraft')()
  File "/usr/lib/python2.7/site-packages/shellcraft-0.9.2-py2.7.egg/shellcraft/cli.py", line 61, in main
    game = get_game(game_path)
  File "/usr/lib/python2.7/site-packages/shellcraft-0.9.2-py2.7.egg/shellcraft/cli.py", line 23, in get_game
    GAME = Game.load(path) if os.path.exists(path) else Game.create(path)
  File "/usr/lib/python2.7/site-packages/shellcraft-0.9.2-py2.7.egg/shellcraft/shellcraft.py", line 184, in load
    state = json_format.Parse(f.read(), GameState())
  File "/usr/lib/python2.7/site-packages/protobuf-3.3.0-py2.7.egg/google/protobuf/json_format.py", line 369, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/usr/lib/python2.7/site-packages/protobuf-3.3.0-py2.7.egg/google/protobuf/json_format.py", line 384, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/usr/lib/python2.7/site-packages/protobuf-3.3.0-py2.7.egg/google/protobuf/json_format.py", line 415, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/lib/python2.7/site-packages/protobuf-3.3.0-py2.7.egg/google/protobuf/json_format.py", line 501, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse action field: Failed to parse completion field: time data '2017-07' does not match format '%Y-%m-%dT%H:%M:%S'.
```

**Comment by justinbass** [comment]
This was a weird quirk caused by loading 0.6 and then 0.9 - the old config was not removed elegantly. Removing my config fixed the issue. Plays great so far!
