### ISSUE TITLE
Commands in multiple shells prompts stack trace

### ISSUE THREAD

**Issue by justinbass** [maebert/shellcraft#5]
* ShellCraft version: 0.9.2
* Python version: 2.7.9
* Operating System: Windows 10 running cygwin

### Description

Opened new shell window and tried performing "mine clay" in both shells. Stack trace displays (instead of an elegant error message).

### What I Did

```
$ shellcraft mine clay
Traceback (most recent call last):
  File "/usr/bin/shellcraft", line 9, in <module>
    load_entry_point('shellcraft==0.9.2', 'console_scripts', 'shellcraft')()
  File "/usr/lib/python2.7/site-packages/shellcraft-0.9.2-py2.7.egg/shellcraft/cli.py", line 75, in main
    cli()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/shellcraft-0.9.2-py2.7.egg/shellcraft/cli.py", line 31, in inner
    callback(**kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/shellcraft-0.9.2-py2.7.egg/shellcraft/cli.py", line 106, in mine
    duration, quantity = game.mine(resource)
TypeError: 'NoneType' object is not iterable
```

**Comment by maebert** [comment]
Hey Justin, thanks for reporting this! Shellcraft is very much WIP, but I'll fix this asap!
