### ISSUE TITLE
Error on shellcraft resources

### ISSUE THREAD

**Issue by justinbass** [maebert/shellcraft#6]
* ShellCraft version: 0.9.2
* Python version: 2.7.9
* Operating System: Windows 10 running cygwin

### Description

Followed tutorial exactly until researching small_cart, then ran shellcraft resources and got a stack trace.

### What I Did

```
$ shellcraft resources
Traceback (most recent call last):
  File "/usr/bin/shellcraft", line 9, in <module>
    load_entry_point('shellcraft==0.9.2', 'console_scripts', 'shellcraft')()
  File "/usr/lib/python2.7/site-packages/shellcraft-0.9.2-py2.7.egg/shellcraft/cli.py", line 75, in main
    cli()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/shellcraft-0.9.2-py2.7.egg/shellcraft/cli.py", line 157, in resources
    echo("*{}: {}*", resource, game.resources.get(resource))
  File "/usr/lib/python2.7/site-packages/shellcraft-0.9.2-py2.7.egg/shellcraft/_cli_impl.py", line 178, in echo
    s = s.format(*vals)
IndexError: tuple index out of range
```

**Comment by maebert** [comment]
Should be fixed in 0.9.3 now :)
